version: 0.2

phases:
  pre_build:
    commands: 
      - pip install --upgrade pip
      - pip install huggingface_hub 

  build:
    commands:
      - echo Build started on `date`
      - echo Downloading and packaging the model...
      - echo clean working directory
      - bash scripts/package_model.sh $MODEL_BUCKET_NAME 
      - echo Model packaging completed.

  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploaded model to S3 bucket...

artifacts:
  files: 
    - '**/*'


   