version: 0.2

env:
  variables:
    REGION: "ca-central-1"
    ECR_REPOSITORY: "stablelm-3b-inference"
    IMAGE_REPO_NAME: "stablelm-3b-inference"
    AWS_ACCOUNT_ID: "252312373833"
    MODEL_BUCKET_NAME: "llmmlopsstack-llmmodelbucketece4678b-w6dy6zds3hxs"

phases:
  pre_build:
    commands: 
      - pip install --upgrade pip
      - pip install huggingface_hub 

  build:
    commands:
      - echo Build started on `date`
      - echo Downloading and packaging the model...
      - echo clean working directory
      - bash ../scripts/package_model.sh $MODEL_BUCKET_NAME
      - echo Model packaging completed.

  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading model to S3 bucket...

artifacts:
  files: 
    - '**/*'


   